services:

  olx-monitor:
    build: .
    restart: unless-stopped
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - ./src/config.ts:/usr/app/config.ts
      - ./src/.env:/usr/app/.env
      - ./data:/usr/data